nav:
    - Getting Started:
          - Introduction: index.md
          - Testing locally: Testing.md
          - Configuration: Configuration.md
          - Deployment: Deployment.md
          - User system: Users.md
    - API specification: api.md
    - Developer Guide:
          - Development environment: Development-instructions.md
site_name: Gramps Web API
site_url: https://gramps-project.github.io/gramps-webapi
repo_url: https://github.com/gramps-project/gramps-webapi
edit_uri: https://github.com/gramps-project/gramps-webapi/blob/master/docs/
theme:
    name: "material"
    features:
        - navigation.tabs
        - navigation.instant
    palette:
        scheme: default
        primary: brown
        accent: blue
    logo: logo.svg
plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
